### ISSUE TITLE
Multiple Contact Point Bug

### ISSUE THREAD

**Issue by mtear** [RandyGaul/ImpulseEngine#4]
Hey,

There is are issues in the Manifold Resolution portion when there are two contact points in the collision.

For one, an impulse is applied to the Body after the first contact point is processed and then the velocity and angularVelocity are used in the for loop for the next contact point but those values have already been modified.

Secondly the impulse algorithm doesn't work correctly when two contact points are made. Box2D seems to have some sort of Box Solver algorithm to handle this. For example, send a rectangle at a larger rectangle with infinite mass and the moving rectangle will not bounce correctly. It will start to rotate when it shouldn't and more often than not get stuck. The impulses of the two points need to be combined somehow and not applied separately.

**Comment by RandyGaul** [comment]
It's a good learning exercise to try and implement an iterative solver that converges to the global minimum. This code intentionally does not implement such a solver, and instead naively applies impulses in isolation. Read more of Erin Catto's resources if you'd like to delve deeper into this topic. A good test would be to convert ImpulseEngine into an iterative solver.

**Comment by mtear** [comment]
Ah yes that seems to be what Box2D is doing. Any pointers in the right direction to resources would be very appreciated :) I have been porting Impulse to C# but wanted to make the solving more accurate.
It may just be my ignorance but why would taking the vectors rA and rB and adding them and applying the impulse to just the sum not work?

**Comment by RandyGaul** [comment]
rA and rB should be pointing to the same location in world space. They are used to transform from rigid body local space, to world space, or vise versa. Since we compute an impulse along a world space direction, and want to apply this impulse in an equal and opposite manner across both bodies, we must rA and rB from each body respectively.

As for tips I'd suggest looking into Box2D *Lite* (not the full version). Try to implement the iterative solver without warm starting. The difficult part is tracking touching bodies over multiple frames, and tracking different contact points over multiple frames. From here it's a matter of clamping the accumulated impulse.

**Comment by RandyGaul** [comment]
Found some pseudo code from an old email of someone implementing an iterative solver in ImpulseEngine:

`// calculate j scalar
float j = calculate( );

// Clamp j to the accumulated impulse
float temp = contact->cache;
contact->cache = Max( temp + j, 0.0f );
j = contact->cache - temp;

// Apply j like normal`

And then once this is working make sure to remove the old position projection in ImpulseEngine. You will now see constraint drift if implemented properly. This can be solved with the Baumgarte technique:

`const float k_baumgarte = 0.2f;
const float k_slop = 0.05f;

// Calculate bias term
float b = k_baumgarte * (1.0f / dt) * min( 0.0f, penetration + k_slop );

// calculate j scalar
float j = calculate( ) + b;

// Clamp j to the accumulated impulse
float temp = contact->cache;
contact->cache = Max( temp + j, 0.0f );
j = contact->cache - temp;
// Apply j like normal`

You can check out my other 3D code example here on github as well as Box2D *Lite* for additional references.
