### ISSUE TITLE
Circle friction not working as intended? Circle never gets any slower.

### ISSUE THREAD

**Issue by Fahersto** [RandyGaul/ImpulseEngine#9]
I'm currently stuck with friction and wanted to check out this repo to see how it works. It seems though that circles never stop. I tried to debug it and it seems that friction attempts to slow the circle down but it always gets overshadowed by other forces making it faster. So even when colliding with the flat ground the circle will wander off.  I tried cranking up dynamic and static friction but that also didnt help. Am I missing something?

P.S. Thank you for your great tutorial series.

**Comment by RandyGaul** [comment]
The friction works to stop sliding, but there's nothing in the code for rolling. The easiest way to get circles to eventually stop rolling is probably to use some velocity damping. It's an indirect solution and does not really address the underlying problem, but it will work.

Example from Box2D:
https://github.com/erincatto/box2d/blob/95f74a46c077825478f989df6a81003ca538c2c2/src/dynamics/b2_island.cpp#L214-L222

**Comment by Fahersto** [comment]
I understand. Thank you for answering my question, I will give this a try. Id really like to write my physics based on your tutorials as its the first time I actually understand most of it 👍

**Comment by Fahersto** [comment]
Working great, thank you again! :)
